# Generated by Django 5.0.3 on 2024-04-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_alter_sitebanner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('article_list ', 'صفحه لیست مقالات'), ('about_us', 'درباره ما')], max_length=200, verbose_name='جایگاه نمایشی'),
        ),
    ]
