# Generated by Django 5.0.3 on 2024-03-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_in_english', models.CharField(max_length=300, verbose_name='نام مقاله به انگلیسی')),
                ('title_in_persian', models.CharField(max_length=300, verbose_name='نام مقاله به فارسی')),
                ('image', models.ImageField(upload_to='images/articles', verbose_name='تصویر فایل')),
                ('articles_file', models.FileField(upload_to='articles_files', verbose_name='قایل مقاله')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار مقاله')),
                ('count_pages', models.IntegerField(verbose_name='تعداد صفحات مقاله')),
                ('journal', models.CharField(blank=True, max_length=300, null=True, verbose_name='مجله')),
                ('university', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام دانشگاه')),
                ('free_or_buyable', models.BooleanField(verbose_name='رایگان/فروشی')),
                ('price', models.CharField(blank=True, max_length=20, null=True, verbose_name='قیمت')),
                ('abstract', models.TextField(verbose_name='چکیده')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('category', models.ManyToManyField(related_name='article_categories', to='article_module.articlecategory', verbose_name='دسته بندی مقالات')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
