# Generated by Django 5.0.3 on 2024-03-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ انتشار مقاله'),
        ),
    ]
